# Generated by Django 5.2.2 on 2026-02-27 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('sort', models.IntegerField(default=0)),
                ('is_all', models.BooleanField(default=False)),
                ('total_count', models.IntegerField(default=1)),
                ('used_count', models.IntegerField(default=0)),
                ('separate_count', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'prize',
            },
        ),
        migrations.CreateModel(
            name='DrawBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draw_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', '待确认'), ('CONFIRMED', '已确认'), ('VOID', '已作废')], default='PENDING', max_length=16)),
                ('draw_scope', models.JSONField(blank=True, default=dict)),
                ('void_reason', models.CharField(blank=True, default='', max_length=255)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_draw_batches', to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draw_batches', to='lottery.prize')),
            ],
            options={
                'db_table': 'draw_batch',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.department')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='prize',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='lottery.project'),
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='PENDING', max_length=16)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='lottery.project')),
            ],
            options={
                'db_table': 'export_job',
            },
        ),
        migrations.CreateModel(
            name='ExclusionRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('EXCLUDE_SOURCE_WINNERS', '排除来源中奖人')], default='EXCLUDE_SOURCE_WINNERS', max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('source_prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_rules', to='lottery.prize')),
                ('target_prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_rules', to='lottery.prize')),
                ('source_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rules', to='lottery.project')),
                ('target_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rules', to='lottery.project')),
            ],
            options={
                'db_table': 'exclusion_rule',
            },
        ),
        migrations.CreateModel(
            name='DrawWinner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '待确认'), ('CONFIRMED', '已确认'), ('VOID', '已作废')], default='PENDING', max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='lottery.drawbatch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner_records', to='lottery.customer')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winners', to='lottery.prize')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='lottery.project')),
            ],
            options={
                'db_table': 'draw_winner',
            },
        ),
        migrations.AddField(
            model_name='drawbatch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_batches', to='lottery.project'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_members', to='lottery.customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='lottery.project')),
            ],
            options={
                'db_table': 'project_member',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['department', 'is_active'], name='project_departm_30a3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='project_created_86fac0_idx'),
        ),
        migrations.AddIndex(
            model_name='prize',
            index=models.Index(fields=['project', 'sort'], name='prize_project_f2235b_idx'),
        ),
        migrations.AddIndex(
            model_name='prize',
            index=models.Index(fields=['project', 'is_active'], name='prize_project_4d98d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='prize',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_project_prize_name'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['project', 'status', 'created_at'], name='export_job_project_a47ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='exclusionrule',
            index=models.Index(fields=['target_project', 'target_prize', 'is_enabled'], name='exclusion_r_target__7ba97d_idx'),
        ),
        migrations.AddConstraint(
            model_name='exclusionrule',
            constraint=models.UniqueConstraint(fields=('source_project', 'source_prize', 'target_project', 'target_prize', 'mode'), name='uniq_exclusion_rule'),
        ),
        migrations.AddIndex(
            model_name='drawwinner',
            index=models.Index(fields=['project', 'prize', 'status'], name='draw_winner_project_39124c_idx'),
        ),
        migrations.AddIndex(
            model_name='drawwinner',
            index=models.Index(fields=['phone'], name='draw_winner_phone_b86680_idx'),
        ),
        migrations.AddConstraint(
            model_name='drawwinner',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('project', 'prize', 'customer'), name='uniq_confirmed_winner_per_prize'),
        ),
        migrations.AddIndex(
            model_name='drawbatch',
            index=models.Index(fields=['project', 'prize', 'status'], name='draw_batch_project_bc76ae_idx'),
        ),
        migrations.AddIndex(
            model_name='drawbatch',
            index=models.Index(fields=['created_at'], name='draw_batch_created_cdbb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'is_active'], name='project_mem_project_3db0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'uid'], name='project_mem_project_1e084d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['phone'], name='project_mem_phone_d91bdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'customer'), name='uniq_project_customer'),
        ),
    ]
