# Generated by Django 5.2.2 on 2026-03-09 15:26

import django.db.models.deletion
from django.db import migrations, models


def backfill_customer_stats(apps, schema_editor):
    Customer = apps.get_model("lottery", "Customer")
    ProjectMember = apps.get_model("lottery", "ProjectMember")
    DrawWinner = apps.get_model("lottery", "DrawWinner")

    for customer in Customer.objects.all().iterator():
        members = ProjectMember.objects.filter(customer_id=customer.phone)
        first_member = members.order_by("created_at", "id").first()
        participated_project_count = members.values("project_id").distinct().count()
        claimed_prize_count = DrawWinner.objects.filter(
            customer_id=customer.phone,
            status="CONFIRMED",
            is_prize_claimed=True,
        ).count()

        Customer.objects.filter(phone=customer.phone).update(
            participated_project_count=participated_project_count,
            claimed_prize_count=claimed_prize_count,
            first_project_id=(first_member.project_id if first_member else None),
            first_participated_at=(first_member.created_at if first_member else None),
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户管理'},
        ),
        migrations.AlterModelOptions(
            name='drawbatch',
            options={'verbose_name': '抽奖批次', 'verbose_name_plural': '抽奖批次管理'},
        ),
        migrations.AlterModelOptions(
            name='drawwinner',
            options={'verbose_name': '中奖记录', 'verbose_name_plural': '中奖记录管理'},
        ),
        migrations.AlterModelOptions(
            name='exclusionrule',
            options={'verbose_name': '排除规则', 'verbose_name_plural': '排除规则管理'},
        ),
        migrations.AlterModelOptions(
            name='exportjob',
            options={'verbose_name': '导出任务', 'verbose_name_plural': '导出任务管理'},
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'verbose_name': '奖项', 'verbose_name_plural': '奖项管理'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目管理'},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'verbose_name': '项目成员', 'verbose_name_plural': '项目成员管理'},
        ),
        migrations.AddField(
            model_name='customer',
            name='claimed_prize_count',
            field=models.PositiveIntegerField(default=0, verbose_name='领取奖品次数'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_participated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次参与时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_participated_customers', to='lottery.project', verbose_name='首次参与项目'),
        ),
        migrations.AddField(
            model_name='customer',
            name='participated_project_count',
            field=models.PositiveIntegerField(default=0, verbose_name='参与活动次数'),
        ),
        migrations.AddField(
            model_name='drawwinner',
            name='claim_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='领奖备注'),
        ),
        migrations.AddField(
            model_name='drawwinner',
            name='is_prize_claimed',
            field=models.BooleanField(default=False, verbose_name='是否已领取奖品'),
        ),
        migrations.AddField(
            model_name='drawwinner',
            name='is_visited',
            field=models.BooleanField(default=False, verbose_name='是否到访'),
        ),
        migrations.AddField(
            model_name='drawwinner',
            name='prize_claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='领奖时间'),
        ),
        migrations.AddField(
            model_name='drawwinner',
            name='visited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到访时间'),
        ),
        migrations.AddIndex(
            model_name='drawwinner',
            index=models.Index(fields=['project', 'is_prize_claimed'], name='draw_winner_project_bff5b4_idx'),
        ),
        migrations.RunPython(backfill_customer_stats, noop_reverse),
    ]
