# Generated by Django 5.2.2 on 2026-03-15 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_alter_customer_options_alter_drawbatch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MustWinEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_must_win_entries', to='lottery.drawwinner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_must_win_entries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='must_win_entries', to='lottery.customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='must_win_entries', to='lottery.project')),
            ],
            options={
                'verbose_name': '内定必中奖',
                'verbose_name_plural': '内定必中奖',
                'db_table': 'must_win_entry',
                'indexes': [models.Index(fields=['project', 'is_active'], name='must_win_en_project_473d04_idx'), models.Index(fields=['phone'], name='must_win_en_phone_c51a9b_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'customer'), name='uniq_must_win_project_customer')],
            },
        ),
    ]
