# Generated by Django 5.2.2 on 2026-03-15 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_mustwinentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mustwinentry',
            name='target_prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='must_win_entries', to='lottery.prize', verbose_name='指定奖项（为空表示不限奖项）'),
        ),
    ]
