# Generated by Django 5.2.2 on 2026-03-15 06:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_mustwinentry_target_prize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalVisit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('is_winner', models.BooleanField(default=False, verbose_name='是否中奖客户')),
                ('is_prize_claimed', models.BooleanField(default=True, verbose_name='是否领取礼品')),
                ('claim_note', models.CharField(blank=True, default='', max_length=255, verbose_name='到访备注')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='到访时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_visits', to='lottery.customer')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_visits', to='lottery.prize')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_visits', to='lottery.project')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_arrival_visits', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_visits', to='lottery.drawwinner')),
            ],
            options={
                'verbose_name': '到访登记',
                'verbose_name_plural': '到访登记',
                'db_table': 'arrival_visit',
                'indexes': [models.Index(fields=['project', 'visited_at'], name='arrival_vis_project_ba2659_idx'), models.Index(fields=['project', 'phone'], name='arrival_vis_project_164908_idx')],
            },
        ),
    ]
