# Generated by Django 5.2.2 on 2026-03-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': '管理员账号', 'verbose_name_plural': '管理员账号'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id'], 'verbose_name': '部门', 'verbose_name_plural': '部门管理'},
        ),
    ]
