-- V1 schema reference (aligned with Django models)

create table if not exists department (
  id bigserial primary key,
  code varchar(64) not null unique,
  name varchar(128) not null unique,
  region varchar(128) not null default ''
);

create table if not exists admin_user (
  id bigint generated by default as identity primary key,
  password varchar(128) not null,
  last_login timestamp with time zone,
  is_superuser boolean not null,
  username varchar(150) not null unique,
  first_name varchar(150) not null default '',
  last_name varchar(150) not null default '',
  email varchar(254) not null default '',
  is_staff boolean not null,
  is_active boolean not null,
  date_joined timestamp with time zone not null,
  role varchar(32) not null default 'OPERATOR',
  department_id bigint references department(id) on delete set null
);

create table if not exists customer (
  phone varchar(20) primary key,
  name varchar(128) not null default '',
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);

create table if not exists project (
  id uuid primary key,
  code varchar(64) not null unique,
  name varchar(128) not null,
  department_id bigint not null references department(id) on delete restrict,
  region varchar(128) not null default '',
  description text not null default '',
  is_active boolean not null default true,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);

create table if not exists project_member (
  id bigserial primary key,
  project_id uuid not null references project(id) on delete cascade,
  customer_phone varchar(20) not null references customer(phone) on delete restrict,
  uid varchar(64) not null,
  name varchar(128) not null,
  phone varchar(20) not null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  unique(project_id, customer_phone)
);

create table if not exists prize (
  id uuid primary key,
  project_id uuid not null references project(id) on delete cascade,
  name varchar(128) not null,
  sort integer not null default 0,
  is_all boolean not null default false,
  total_count integer not null default 1,
  used_count integer not null default 0,
  separate_count jsonb not null default '{}'::jsonb,
  description text not null default '',
  is_active boolean not null default true,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  unique(project_id, name)
);

create table if not exists draw_batch (
  id uuid primary key,
  project_id uuid not null references project(id) on delete cascade,
  prize_id uuid not null references prize(id) on delete restrict,
  requested_by_id bigint not null references admin_user(id) on delete restrict,
  draw_count integer not null default 1,
  status varchar(16) not null default 'PENDING',
  draw_scope jsonb not null default '{}'::jsonb,
  void_reason varchar(255) not null default '',
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);

create table if not exists draw_winner (
  id uuid primary key,
  batch_id uuid not null references draw_batch(id) on delete cascade,
  project_id uuid not null references project(id) on delete cascade,
  prize_id uuid not null references prize(id) on delete restrict,
  customer_phone varchar(20) not null references customer(phone) on delete restrict,
  uid varchar(64) not null,
  name varchar(128) not null,
  phone varchar(20) not null,
  status varchar(16) not null default 'PENDING',
  confirmed_at timestamp with time zone,
  void_reason varchar(255) not null default '',
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);

create unique index if not exists uniq_confirmed_winner_per_prize
on draw_winner(project_id, prize_id, customer_phone)
where status = 'CONFIRMED';

create table if not exists exclusion_rule (
  id uuid primary key,
  source_project_id uuid not null references project(id) on delete cascade,
  source_prize_id uuid references prize(id) on delete cascade,
  target_project_id uuid not null references project(id) on delete cascade,
  target_prize_id uuid references prize(id) on delete cascade,
  mode varchar(64) not null default 'EXCLUDE_SOURCE_WINNERS',
  is_enabled boolean not null default true,
  description varchar(255) not null default '',
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  unique(source_project_id, source_prize_id, target_project_id, target_prize_id, mode)
);

create table if not exists export_job (
  id uuid primary key,
  project_id uuid not null references project(id) on delete cascade,
  requested_by_id bigint not null references admin_user(id) on delete restrict,
  filters jsonb not null default '{}'::jsonb,
  status varchar(16) not null default 'PENDING',
  file_path varchar(512) not null default '',
  error_message varchar(255) not null default '',
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);
